# .air.toml
[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "${bin}"
watch_exts = ["go", "tpl", "tmpl", "html"]

[log]
level = "debug"

[color]
main = "cyan"
watcher = "magenta"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true